version: '3'

networks:
  appnet:

volumes:
  appval:

services:
  nwdb:
    image: kubernetes4ts/nwdb:v1
    build: 
      context: ./database
    environment:
    - MYSQL_ROOT_PASSWORD=changeit
    networks:
    - appnet
    volumes:
    - appvol:/var/lib/mysql

  nwapp:
    image: kubernetes4ts/nwapp:latest
    build:
      context: ./server
    environment:
    - DB_HOST=nwdb
    ports:
    - 80:3000
    networks:
    - appnet