version: '3'

networks:
  appnet:

volumes:
  appvol:

services:
  nwdb:
    image: kubernetes4ts/tsdb:v1
    build: 
      context: ./database
    environment:
      - MYSQL_ROOT_PASSWORD=changeit
    networks:
      - appnet
    volumes:
      - appvol:/var/lib/mysql

  nwapp:
    image: kubernetes4ts/tsdbapp:latest
    build:
      context: ./server
    environment:
      - DB_HOST=nwdb
    ports:
      - 80:3000
    networks:
      - appnet